# This is a basic workflow to help you get started with Actions

name: Build_GSI
on:
  workflow_dispatch:
  watch:
    types: [started]
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Build
         run: |       
           sudo apt-get -y update && sudo apt-get -y upgrade && sudo apt-get -y install git
           git clone --recurse-submodules https://github.com/kmou424/ErfanGSIs.git --depth=1
           cd ErfanGSIs
           git clone https://github.com/kmou424/auto_build_gsi build_scripts
           source build_scripts/build.sh
