# This is a basic workflow to help you get started with Actions

name: Build_GSI
on: [workflow_dispatch, pull_request]

env:
  token: ${{ secrets.BOT_TOKEN }}
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Build
         run: |       
           sudo apt-get -y update && sudo apt-get -y upgrade && sudo apt-get -y install git
           git clone --recurse-submodules https://github.com/kmou424/ErfanGSIs.git --depth=1
           cd ErfanGSIs
           git clone https://github.com/kmou424/auto_build_gsi build_scripts
           source build_scripts/build.sh
       - name: Release
         uses: softprops/action-gh-release@v1
         with:
           name: ${{ env.RELEASE_TAG }}-Erfan
           tag_name: ${{ env.RELEASE_TAG }}-Erfan
           files: |
             ErfanGSIs/*.7z
             ErfanGSIs/*.txt
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       - name: Upload
         run: |
           cd ErfanGSIs/build_scripts
           source upload.sh "Erfan"
         env:
           RELEASE_TAG_NAME: ${{ env.RELEASE_TAG }}
